import type { Bot } from 'grammy';
import { accountKeyboard } from '../../features/account/keyboards';
import { renderAccount } from '../../features/account/screens';
import { toolsKeyboard, toolsText, searchKeyboard, searchText } from '../../features/tools/screens';
import { mainMenuKeyboard } from '../ui/main-menu';
import { createRuntime } from '../runtime';
import type { Env } from '../../env';

export function configureTelegramRoutes(bot: Bot, env: Env, executionContext?: ExecutionContext): void {
  const runtime = createRuntime(env);
  bot.command('start', async (ctx) => await ctx.reply('Добро пожаловать в Qelvion-AI.', { reply_markup: mainMenuKeyboard() }));
  bot.command('admin', async (ctx) => { if (!ctx.from || !env.ADMIN_TELEGRAM_IDS?.split(',').map((value) => value.trim()).includes(String(ctx.from.id))) return void await ctx.reply('Доступ запрещён.'); if (!env.ADMIN_MINI_APP_URL) return void await ctx.reply('Admin Panel не настроена. Укажите ADMIN_MINI_APP_URL в Worker configuration.'); await ctx.reply('Откройте Admin Panel:', { reply_markup: { inline_keyboard: [[{ text: 'Admin Panel', web_app: { url: env.ADMIN_MINI_APP_URL } }]] } }); });
  const isAdmin = (id?: number) => Boolean(id && env.ADMIN_TELEGRAM_IDS?.split(',').map((value) => value.trim()).includes(String(id)));
  bot.command('admin_stats', async (ctx) => { if (!isAdmin(ctx.from?.id)) return void await ctx.reply('Доступ запрещён.'); const ops = await runtime.recentOperations(); await ctx.reply(`Recent operations: ${ops.length}`); });
  bot.command('admin_user', async (ctx) => { if (!isAdmin(ctx.from?.id)) return void await ctx.reply('Доступ запрещён.'); const text = ctx.message?.text ?? ''; const telegramId = Number(text.split(/\s+/)[1]); if (!Number.isSafeInteger(telegramId)) return void await ctx.reply('Использование: /admin_user <telegram_id>'); const user = await runtime.users.findByTelegramId(telegramId); await ctx.reply(user ? JSON.stringify({ id: user.id, telegramUserId: user.telegram_user_id, status: user.status, balance: user.balance_points, subscription: user.subscription_status }) : 'Пользователь не найден.'); });
  bot.command('admin_models', async (ctx) => { if (!isAdmin(ctx.from?.id)) return void await ctx.reply('Доступ запрещён.'); const models = await runtime.models.list(); await ctx.reply(models.map((m) => `${m.key} · ${m.provider}:${m.providerModelId} · active`).join('\n') || 'Моделей нет.'); });
  bot.command('admin_points', async (ctx) => { if (!isAdmin(ctx.from?.id)) return void await ctx.reply('Доступ запрещён.'); await ctx.reply('Изменение points выполняется через защищённый Admin Mini App, где действие проходит через ledger и audit.'); });
  bot.command('admin_block', async (ctx) => { if (!isAdmin(ctx.from?.id)) return void await ctx.reply('Доступ запрещён.'); const telegramId = Number((ctx.message?.text ?? '').split(/\s+/)[1]); const user = await runtime.users.findByTelegramId(telegramId); if (!user) return void await ctx.reply('Пользователь не найден.'); await env.QELVION_DB.prepare("UPDATE users SET status = 'blocked', updated_at = ? WHERE id = ?").bind(new Date().toISOString(), user.id).run(); await env.QELVION_DB.prepare('INSERT INTO admin_audit (audit_id, admin_telegram_id, target_user_id, action, before_json, after_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(crypto.randomUUID(), ctx.from!.id, user.id, 'user.block', JSON.stringify({ status: user.status }), JSON.stringify({ status: 'blocked' }), new Date().toISOString()).run(); await ctx.reply('Пользователь заблокирован.'); });
  bot.command('admin_unblock', async (ctx) => { if (!isAdmin(ctx.from?.id)) return void await ctx.reply('Доступ запрещён.'); const telegramId = Number((ctx.message?.text ?? '').split(/\s+/)[1]); const user = await runtime.users.findByTelegramId(telegramId); if (!user) return void await ctx.reply('Пользователь не найден.'); await env.QELVION_DB.prepare("UPDATE users SET status = 'active', updated_at = ? WHERE id = ?").bind(new Date().toISOString(), user.id).run(); await env.QELVION_DB.prepare('INSERT INTO admin_audit (audit_id, admin_telegram_id, target_user_id, action, before_json, after_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(crypto.randomUUID(), ctx.from!.id, user.id, 'user.unblock', JSON.stringify({ status: user.status }), JSON.stringify({ status: 'active' }), new Date().toISOString()).run(); await ctx.reply('Пользователь разблокирован.'); });
  bot.hears('💬 Чат', async (ctx) => { if (ctx.from) await runtime.users.setMode((await runtime.users.getOrCreate(ctx.from.id)).id, 'chat'); await ctx.reply('💬 Чат\n\nОтправьте запрос следующим сообщением.'); });
  bot.hears('🎨 Изображения', async (ctx) => { if (!ctx.from) return; const user = await runtime.users.getOrCreate(ctx.from.id); await runtime.users.setPendingTask(user.id, 'image'); await ctx.reply('🎨 Изображения\n\nОтправьте описание изображения. Запрос будет выполнен через HEAVY_TASK_QUEUE.'); });
  bot.hears('🤖 Модели', async (ctx) => await ctx.reply('🤖 Модели\n\nДоступность управляется Model Registry.'));
  bot.hears('🗂 Диалоги', async (ctx) => await ctx.reply('🗂 Диалоги\n\nАктивные и архивные диалоги управляются тарифными лимитами.'));
  bot.hears('🛠 Инструменты', async (ctx) => await ctx.reply(toolsText(), { reply_markup: toolsKeyboard() }));
  bot.hears('👤 Аккаунт', async (ctx) => { const user = ctx.from ? await runtime.prepareUser(ctx.from.id) : null; await ctx.reply(renderAccount({ balance: user?.balance_points ?? 0, dailyPoints: user?.daily_points_remaining ?? 0, nextDailyRefill: user?.daily_points_reset_at ?? '—', status: user?.subscription_status ?? 'free' }), { reply_markup: accountKeyboard() }); });
  bot.callbackQuery('tools:search', async (ctx) => { await ctx.answerCallbackQuery(); if (ctx.from) { const user = await runtime.users.getOrCreate(ctx.from.id); await runtime.users.setMode(user.id, 'search'); } await ctx.reply(searchText(), { reply_markup: searchKeyboard() }); });
  bot.callbackQuery('tools:search:exit', async (ctx) => { await ctx.answerCallbackQuery(); if (ctx.from) { const user = await runtime.users.getOrCreate(ctx.from.id); await runtime.users.setMode(user.id, 'chat'); } await ctx.reply('Вы вышли из Search Mode.', { reply_markup: toolsKeyboard() }); });
  bot.callbackQuery(/^account:/, async (ctx) => { await ctx.answerCallbackQuery(); await ctx.editMessageText(`👤 Аккаунт\n\nРаздел: ${ctx.callbackQuery.data.slice('account:'.length)}`); });
  bot.callbackQuery(/^tools:/, async (ctx) => { await ctx.answerCallbackQuery(); const key = ctx.callbackQuery.data.slice('tools:'.length); if (key !== 'search') { if (ctx.from && (key === 'documents' || key === 'voice' || key === 'audio')) { const user = await runtime.users.getOrCreate(ctx.from.id); await runtime.users.setPendingTask(user.id, key === 'documents' ? 'document' : key === 'audio' ? 'audio' : 'voice'); await ctx.reply(key === 'documents' ? '📄 Документы\n\nОтправьте текст задания для документа.' : key === 'audio' ? '🎵 Аудио\n\nОтправьте текст, который нужно озвучить как аудиофайл.' : '🎙 Голос\n\nОтправьте текст, который нужно озвучить как голосовое сообщение.'); } else await ctx.reply(`🛠 Инструмент: ${key}`); } });
  bot.on('callback_query:data', async (ctx) => await ctx.answerCallbackQuery());
  bot.on('message:text', async (ctx) => { const text = ctx.message.text.trim(); if (text.startsWith('/')) return; if (!ctx.from) return; try { const activeUser = await runtime.users.getOrCreate(ctx.from.id); if (activeUser.pending_task_type) { const type = activeUser.pending_task_type; await runtime.users.setPendingTask(activeUser.id, null); await runtime.enqueueMedia(ctx.from.id, type, text, `telegram:${ctx.update.update_id}`); await ctx.reply('⏳ Запрос поставлен в очередь. Результат придёт отдельным сообщением.'); return; } if (activeUser.active_mode === 'search') { const requestId = `telegram:${ctx.update.update_id}`; const chatId = ctx.chat?.id; if (!chatId) return; const searchJob = (async () => { try { const result = await runtime.search(ctx.from.id, text, requestId); const sourceText = result.sources.length ? `\n\nИсточники:\n${result.sources.map((url, i) => `${i + 1}. ${url}`).join('\n')}` : ''; await bot.api.sendMessage(chatId, result.answer + sourceText, { link_preview_options: { is_disabled: true }, reply_markup: searchKeyboard() }); } catch { await bot.api.sendMessage(chatId, 'Поиск не завершился вовремя или сервис поиска временно недоступен. Попробуйте ещё раз позже.', { reply_markup: searchKeyboard() }); } })(); if (executionContext) { executionContext.waitUntil(searchJob); await ctx.reply('🔎 Ищу информацию…'); } else { await searchJob; } return; } await ctx.reply(await runtime.chat(ctx.from.id, text, `telegram:${ctx.update.update_id}`)); } catch { await ctx.reply('Не удалось выполнить запрос. Попробуйте ещё раз позже.'); } });
}
